#' Download data from AppEEARS
#'
#' Downloads data files associated with a specific task from AppEEARS.
#'
#' @param task_id The ID of the task generated by the function `submit_processing_task` or an ID for a task in AppEEARS.
#' @param token The access token generated during the login process (`appeears_login`).
#' @param output_directory The directory where the downloaded files will be saved.
#'
#' @return Returns the status of the download process.
#'
#' @importFrom httr GET add_headers content write_disk progress
#' @importFrom jsonlite fromJSON toJSON prettify
#'
#' @export
#'
download_task_bundle <- function(task_id, token, output_directory) {

  # AppEEARS API base URL
  API_URL <- 'https://appeears.earthdatacloud.nasa.gov/api/'

  # Extract token from JSON object
  token <- paste("Bearer", jsonlite::fromJSON(token)$token)

  # Request the task bundle info from API bundle URL
  response <- httr::GET(paste0(API_URL, "bundle/", task_id), httr::add_headers(Authorization = token))

  # Check for successful response
  if (httr::http_error(response)) {
    stop("Failed to retrieve task bundle information.")
  }

  # Retrieve content of the request
  response_content <- httr::content(response)

  # Convert the content to JSON object
  bundle_response <- jsonlite::toJSON(response_content, auto_unbox = TRUE)

  # Print the prettified response
  jsonlite::prettify(bundle_response)

  # Extract file information from the bundle
  bundle <- jsonlite::fromJSON(bundle_response)$files

  # Download each file in the bundle
  for (id in bundle$file_id) {
    # Retrieve the filename from the file_id
    filename <- bundle[bundle$file_id == id,]$file_name
    # Create the destination directory to store the file
    filepath <- file.path(output_directory, filename)
    # Create the destination directory if it doesn't exist
    if (!file.exists(dirname(filepath))) {
      dir.create(dirname(filepath), recursive = TRUE)
    }
    # Download the file and save it to disk
    response <- httr::GET(
      paste0(API_URL, "bundle/", task_id, "/", id),
      httr::write_disk(filepath, overwrite = TRUE),
      httr::progress(),
      httr::add_headers(Authorization = token)
    )

    # Check for successful file download
    if (httr::http_error(response)) {
      warning(paste("Failed to download file:", filename))
    }
  }

  return("Download completed.")
}
