#' download data from AppEEARS
#'
#' @param task_id MANDATORY - the ID generated by the function submit_processing_task or an id for a task in AppEEARS
#' @param token MADATORY - the token generated during the log-in process (appeears_login)
#' @param output_directory MANDATORY - the output directory
#'
#' @return returns the status of the download process
#'
#' @importFrom httr GET
#' @importFrom httr add_headers
#' @importFrom httr content
#' @importFrom httr write_disk
#' @importFrom httr progress
#' @importFrom jsonlite fromJSON
#' @importFrom jsonlite toJSON
#' @importFrom jsonlite prettify
#'
#' @export
#'
#'
download_task_bundle <- function(task_id, token, output_directory){

  API_URL <- 'https://appeears.earthdatacloud.nasa.gov/api/'

  token <- paste("Bearer", jsonlite::fromJSON(token)$token)
  # Request the task bundle info from API bundle URL
  response <- httr::GET(paste0(API_URL, "bundle/", task_id), httr::add_headers(Authorization = token))
  response_content <- httr::content(response)                          # Retrieve content of the request
  bundle_response <- jsonlite::toJSON(response_content, auto_unbox = TRUE)  # Convert the content to JSON object
  jsonlite::prettify(bundle_response)

  bundle <- jsonlite::fromJSON(bundle_response)$files
  for (id in bundle$file_id){
    # retrieve the filename from the file_id
    filename <- bundle[bundle$file_id == id,]$file_name
    # create a destination directory to store the file in
    filepath <- paste(output_directory,filename, sep = "/")
    suppressWarnings(dir.create(dirname(filepath)))
    # write the file to disk using the destination directory and file name
    response <- httr::GET(paste0(API_URL, "bundle/", task_id, "/", id),
                          httr::write_disk(filepath, overwrite = TRUE),
                          httr::progress(),
                          httr::add_headers(Authorization = token))
  }

}
